-- Idempotent PostgreSQL Migration: Add missing columns to users table
-- Safe to execute repeatedly on live Supabase databases

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "firstName" VARCHAR(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "lastName" VARCHAR(255);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "additionalInfo" TEXT DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "googleId" VARCHAR(255) DEFAULT NULL;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "authProvider" VARCHAR(50) DEFAULT 'email';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "acceptedTerms" BOOLEAN DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "termsVersion" VARCHAR(50) DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "lastLogin" TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "firebaseUid" VARCHAR(255) DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "upiId" VARCHAR(255) DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "language" VARCHAR(50) DEFAULT 'en';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "privacyVisibility" VARCHAR(50) DEFAULT 'public';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "notificationPreferences" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "savedDestinations" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS achievements JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "lastActiveDate" VARCHAR(50) DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
