/** @type {import('tailwindcss').Config} */
/** Traveloop unified design system — import in every portal tailwind.config */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    screens: {
      xs: "360px",
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: "#14B8B5",
          light: "#5EEAD4",
          dark: "#0D9488",
          50: "#F0FDFA",
          100: "#CCFBF1",
          200: "#99F6E4",
          300: "#5EEAD4",
          400: "#2DD4BF",
          500: "#14B8B5",
          600: "#0D9488",
          700: "#0F766E",
        },
        secondary: {
          DEFAULT: "#0F172A",
          light: "#1E293B",
          dark: "#020617",
        },
        accent: {
          DEFAULT: "#F59E0B",
          light: "#FCD34D",
          dark: "#D97706",
          50: "#FFFBEB",
          100: "#FEF3C7",
          500: "#F59E0B",
          600: "#D97706",
        },
        surface: "#FFFFFF",
        "surface-2": "#F8FAFC",
        "surface-3": "#F1F5F9",
        background: "#F8FAFC",
        card: "#FFFFFF",
        brand: "#14B8B5",
      },
      fontFamily: {
        sans: ["Inter", "Poppins", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "800", letterSpacing: "-0.02em" }],
        "display-md": ["40px", { lineHeight: "1.12", fontWeight: "800", letterSpacing: "-0.02em" }],
        "display-sm": ["32px", { lineHeight: "1.15", fontWeight: "800", letterSpacing: "-0.01em" }],
        "heading-xl": ["36px", { lineHeight: "1.15", fontWeight: "700", letterSpacing: "-0.01em" }],
        "heading-lg": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "heading-md": ["24px", { lineHeight: "1.25", fontWeight: "700" }],
        "heading-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.65" }],
        "body-md": ["16px", { lineHeight: "1.65" }],
        "body-sm": ["14px", { lineHeight: "1.5" }],
        "card-text": ["15px", { lineHeight: "1.5", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.4" }],
        tiny: ["10px", { lineHeight: "1.4" }],
      },
      maxWidth: {
        content: "1440px",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        card: "var(--shadow-md)",
        "card-hover": "var(--shadow-lg)",
        brand: "var(--shadow-brand)",
        "brand-lg": "0 16px 48px rgba(20,184,181,0.40)",
        nav: "0 -4px 24px rgba(15,23,42,0.08)",
        bar: "0 4px 24px rgba(15,23,42,0.08)",
        float: "var(--shadow-float)",
        glow: "0 0 40px rgba(20,184,181,0.3)",
        "amber-glow": "0 0 32px rgba(245,158,11,0.4)",
      },
      borderRadius: {
        card: "16px",
        "mobile-sm": "12px",
        "mobile-md": "16px",
        "mobile-lg": "20px",
        "mobile-xl": "24px",
        "mobile-2xl": "32px",
        pill: "999px",
      },
      spacing: {
        "content-desktop": "40px",
        "content-tablet": "24px",
        "content-mobile": "16px",
        "section-desktop": "32px",
        "section-tablet": "24px",
        "section-mobile": "16px",
        "safe-top": "env(safe-area-inset-top, 0px)",
        "safe-bottom": "env(safe-area-inset-bottom, 0px)",
        "safe-left": "env(safe-area-inset-left, 0px)",
        "safe-right": "env(safe-area-inset-right, 0px)",
        "app-bar": "60px",
        "bottom-nav": "80px",
        touch: "44px",
        "sidebar-expanded": "260px",
        "sidebar-collapsed": "80px",
      },
      animation: {
        float: "float 3s ease-in-out infinite",
        "fade-in": "fadeIn 300ms ease forwards",
        "fade-in-up": "fadeInUp 400ms cubic-bezier(0.34,1.56,0.64,1) forwards",
        "slide-up": "slideUp 350ms cubic-bezier(0.34,1.56,0.64,1) forwards",
        "slide-up-sheet": "slideUpSheet 380ms cubic-bezier(0.32,0.72,0,1) forwards",
        "slide-down-sheet": "slideDownSheet 300ms cubic-bezier(0.32,0.72,0,1) forwards",
        toast: "toastSlideUp 300ms cubic-bezier(0.34,1.56,0.64,1) forwards",
        page: "pageEnter 300ms ease forwards",
        "scale-in": "scaleIn 300ms cubic-bezier(0.34,1.56,0.64,1) forwards",
        skeleton: "skeletonPulse 1.6s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%,100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideUpSheet: {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        slideDownSheet: {
          from: { transform: "translateY(0)" },
          to: { transform: "translateY(100%)" },
        },
        toastSlideUp: {
          from: { transform: "translateY(100px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        pageEnter: {
          from: { opacity: "0", transform: "translateX(12px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          from: { transform: "scale(0.92)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        skeletonPulse: {
          "0%": { backgroundPosition: "-300px 0" },
          "100%": { backgroundPosition: "calc(300px + 100%) 0" },
        },
      },
      backgroundImage: {
        "gradient-brand": "linear-gradient(135deg, #14B8B5, #0D9488)",
        "gradient-brand-warm": "linear-gradient(135deg, #14B8B5, #F59E0B)",
        "gradient-brand-deep": "linear-gradient(135deg, #0F172A, #14B8B5)",
        "gradient-dark": "linear-gradient(135deg, #0F172A, #1E293B)",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
        snap: "cubic-bezier(0.32, 0.72, 0, 1)",
      },
      backdropBlur: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
      },
    },
  },
  plugins: [],
};
